org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# 工程路径含中文（记账软件），本机为中文 locale，跳过 AGP 的非 ASCII 路径硬检查
android.overridePathCheck=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=true

kotlin.code.style=official
kotlin.incremental=true
